baseURL = 'https://lambocrisis.github.io/'
languageCode = 'zh-CN'
title = '竹林中'
theme = 'typo'

[[params.menu]]
name = "主页"
url = "/"

[[params.menu]]
name = "文章"
url = "/post"

[params]
colorPalette = 'eink'

homeIntroContent = """
地址：竹云馆，瑸市街，滨江区
"""

showFooter = true
footerContent = "久在樊笼里，复得返自然"

listSummaries = false

listDateFormat = '2006 Jan 02'

paginationSize = 20